import type { Exercise } from './types'

export const EXERCISES: Exercise[] = [
  // ── SQUATS ──────────────────────────────────────────────────────────────────
  {
    id: 'air-squat',
    name: 'Air Squat',
    equipment: ['bodyweight'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium', 'long'],
    substitutions: ['box squat', 'sit-to-stand'],
    coachingCue: 'Chest up, knees tracking toes, hit parallel.',
  },
  {
    id: 'jump-squat',
    name: 'Jump Squat',
    equipment: ['bodyweight'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'calves'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['air squat'],
    coachingCue: 'Land soft, absorb through hips and knees.',
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    equipment: ['dumbbells', 'kettlebell'],
    movementPattern: 'squat',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes', 'core'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['air squat'],
    coachingCue: 'Elbows inside knees at bottom, tall chest.',
    rxLoad: { male: '53 lb KB', female: '35 lb KB' },
  },
  {
    id: 'db-front-squat',
    name: 'Dumbbell Front Squat',
    equipment: ['dumbbells'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes', 'core'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['goblet squat', 'air squat'],
    coachingCue: 'DBs on shoulders, elbows high.',
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    equipment: ['barbell'],
    movementPattern: 'squat',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'core'],
    defaultRepRange: [3, 8],
    timeDomainFit: ['short'],
    substitutions: ['db-front-squat', 'goblet-squat'],
    avoidForBeginner: true,
    coachingCue: 'Elbows high, rack position tight, vertical torso.',
    rxLoad: { male: '95 lb', female: '65 lb' },
  },
  {
    id: 'back-squat',
    name: 'Back Squat',
    equipment: ['barbell'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    defaultRepRange: [3, 10],
    timeDomainFit: ['short'],
    substitutions: ['db-front-squat', 'goblet-squat'],
    coachingCue: 'Bar on shelf, brace core, drive knees out.',
    rxLoad: { male: '135 lb', female: '95 lb' },
  },
  {
    id: 'wall-ball',
    name: 'Wall Ball',
    equipment: ['wall_ball'],
    movementPattern: 'squat',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'shoulders'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-thruster', 'goblet-squat'],
    coachingCue: 'Hit parallel, explosive hip drive, aim above target line.',
    rxLoad: { male: '20 lb ball', female: '14 lb ball' },
  },
  {
    id: 'overhead-squat',
    name: 'Overhead Squat',
    equipment: ['barbell'],
    movementPattern: 'squat',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'shoulders', 'core'],
    defaultRepRange: [3, 6],
    timeDomainFit: ['short'],
    substitutions: ['front-squat', 'db-front-squat'],
    avoidForBeginner: true,
    coachingCue: 'Active shoulders, bar over mid-foot, wide grip.',
    rxLoad: { male: '95 lb', female: '65 lb' },
  },
  {
    id: 'pistol',
    name: 'Pistol Squat',
    equipment: ['bodyweight'],
    movementPattern: 'squat',
    difficulty: 'advanced',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes', 'core'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['air squat', 'split squat'],
    avoidForBeginner: true,
    coachingCue: 'Heel down, non-working leg extended forward.',
  },

  // ── HINGES ──────────────────────────────────────────────────────────────────
  {
    id: 'deadlift',
    name: 'Deadlift',
    equipment: ['barbell'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'core'],
    defaultRepRange: [3, 8],
    timeDomainFit: ['short'],
    substitutions: ['db-deadlift', 'kb-deadlift'],
    coachingCue: 'Hinge at hips, neutral spine, bar over mid-foot.',
    rxLoad: { male: '225 lb', female: '155 lb' },
  },
  {
    id: 'db-deadlift',
    name: 'Dumbbell Deadlift',
    equipment: ['dumbbells'],
    movementPattern: 'hinge',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['kb-deadlift', 'good-morning'],
    coachingCue: 'DBs close to legs, flat back, push floor away.',
  },
  {
    id: 'kb-deadlift',
    name: 'Kettlebell Deadlift',
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-deadlift'],
    coachingCue: 'KB between feet, hinge back, proud chest.',
    rxLoad: { male: '53 lb', female: '35 lb' },
  },
  {
    id: 'kb-swing',
    name: 'Kettlebell Swing',
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'shoulders'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-deadlift', 'good-morning'],
    coachingCue: 'Hinge hard, snap hips, KB floats to chest height.',
    rxLoad: { male: '53 lb', female: '35 lb' },
  },
  {
    id: 'american-kb-swing',
    name: 'American Kettlebell Swing',
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'shoulders', 'core'],
    defaultRepRange: [10, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['kb-swing'],
    coachingCue: 'Full hip extension, KB overhead, active shoulders.',
    rxLoad: { male: '53 lb', female: '35 lb' },
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    equipment: ['barbell', 'bodyweight'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    intensity: 'low',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short'],
    substitutions: ['db-deadlift'],
    coachingCue: 'Soft knee, hinge until torso near parallel, neutral spine.',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    equipment: ['barbell', 'dumbbells'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['hamstrings', 'glutes'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short'],
    substitutions: ['db-deadlift', 'good-morning'],
    coachingCue: 'Bar stays close, feel hamstring stretch, hip hinge.',
    rxLoad: { male: '135 lb', female: '95 lb' },
  },

  // ── PUSH ────────────────────────────────────────────────────────────────────
  {
    id: 'push-up',
    name: 'Push-Up',
    equipment: ['bodyweight'],
    movementPattern: 'push',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    defaultRepRange: [8, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['knee push-up', 'incline push-up'],
    coachingCue: 'Rigid plank, elbows back at 45°, full lockout.',
  },
  {
    id: 'knee-push-up',
    name: 'Knee Push-Up',
    equipment: ['bodyweight'],
    movementPattern: 'push',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['chest', 'triceps'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['incline push-up'],
    coachingCue: 'Straight line from knees to shoulders, full range.',
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    equipment: ['bodyweight'],
    movementPattern: 'push',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['shoulders', 'triceps'],
    defaultRepRange: [6, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['push-up', 'db-push-press'],
    coachingCue: 'Hips high, head through at bottom, pressing up and back.',
  },
  {
    id: 'hspu',
    name: 'Handstand Push-Up',
    equipment: ['bodyweight'],
    movementPattern: 'push',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['pike-push-up', 'db-push-press'],
    avoidForBeginner: true,
    coachingCue: 'Tripod base against wall, head touches first, press to full lockout.',
  },
  {
    id: 'strict-press',
    name: 'Strict Press',
    equipment: ['barbell'],
    movementPattern: 'push',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['shoulders', 'triceps'],
    defaultRepRange: [3, 8],
    timeDomainFit: ['short'],
    substitutions: ['db-push-press', 'push-up'],
    coachingCue: 'Elbows in front of bar, press vertically, finish with shrug.',
    rxLoad: { male: '65 lb', female: '45 lb' },
  },
  {
    id: 'push-press',
    name: 'Push Press',
    equipment: ['barbell'],
    movementPattern: 'push',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['shoulders', 'triceps', 'quads'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-push-press', 'strict-press'],
    coachingCue: 'Dip-drive-press: vertical dip, explosive leg drive, lock out.',
    rxLoad: { male: '95 lb', female: '65 lb' },
  },
  {
    id: 'db-push-press',
    name: 'Dumbbell Push Press',
    equipment: ['dumbbells'],
    movementPattern: 'push',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['shoulders', 'triceps', 'quads'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-strict-press', 'push-up'],
    coachingCue: 'DBs at shoulders, dip shallow, press overhead fast.',
    rxLoad: { male: '50 lb DBs', female: '35 lb DBs' },
  },
  {
    id: 'db-strict-press',
    name: 'Dumbbell Strict Press',
    equipment: ['dumbbells'],
    movementPattern: 'push',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['shoulders', 'triceps'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short'],
    substitutions: ['push-up'],
    coachingCue: 'No leg drive, press straight up, full lock out.',
  },
  {
    id: 'thruster',
    name: 'Thruster',
    equipment: ['barbell'],
    movementPattern: 'push',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'shoulders', 'triceps'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-thruster', 'wall-ball'],
    avoidForBeginner: true,
    coachingCue: 'Front squat into push press — one fluid motion, no pause.',
    rxLoad: { male: '95 lb', female: '65 lb' },
  },
  {
    id: 'db-thruster',
    name: 'Dumbbell Thruster',
    equipment: ['dumbbells'],
    movementPattern: 'push',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'shoulders'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-front-squat', 'db-push-press'],
    coachingCue: 'DBs at shoulders, squat deep, drive up and press.',
    rxLoad: { male: '50 lb DBs', female: '35 lb DBs' },
  },

  // ── PULL ────────────────────────────────────────────────────────────────────
  {
    id: 'pull-up',
    name: 'Pull-Up',
    equipment: ['pull_up_bar'],
    movementPattern: 'pull',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['lats', 'biceps', 'upper back'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['ring-row', 'banded-pull-up'],
    coachingCue: 'Dead hang start, chin clears bar, controlled descent.',
  },
  {
    id: 'chest-to-bar',
    name: 'Chest-to-Bar Pull-Up',
    equipment: ['pull_up_bar'],
    movementPattern: 'pull',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['lats', 'biceps', 'upper back'],
    defaultRepRange: [3, 8],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['pull-up', 'ring-row'],
    avoidForBeginner: true,
    coachingCue: 'Chest touches bar, full hip extension at bottom.',
  },
  {
    id: 'muscle-up',
    name: 'Muscle-Up',
    equipment: ['pull_up_bar', 'rings'],
    movementPattern: 'gymnastics',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['lats', 'chest', 'triceps', 'core'],
    defaultRepRange: [3, 7],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['pull-up', 'chest-to-bar'],
    avoidForBeginner: true,
    coachingCue: 'Aggressive kip, early transition, lock out at top.',
  },
  {
    id: 'ring-row',
    name: 'Ring Row',
    equipment: ['rings'],
    movementPattern: 'pull',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['lats', 'biceps', 'upper back'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['banded-pull-up'],
    coachingCue: 'Rigid body, pull rings to chest, squeeze at top.',
  },
  {
    id: 'toes-to-bar',
    name: 'Toes-to-Bar',
    equipment: ['pull_up_bar'],
    movementPattern: 'gymnastics',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['core', 'lats', 'hip flexors'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['hanging-knee-raise', 'sit-up'],
    coachingCue: 'Kip from shoulders, toes touch bar simultaneously.',
  },
  {
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    equipment: ['pull_up_bar'],
    movementPattern: 'core',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['core', 'hip flexors'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['sit-up', 'hollow-hold'],
    coachingCue: 'Controlled, knees to chest, avoid swinging.',
  },
  {
    id: 'db-bent-row',
    name: 'Dumbbell Bent-Over Row',
    equipment: ['dumbbells'],
    movementPattern: 'pull',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['lats', 'upper back', 'biceps'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['ring-row'],
    coachingCue: 'Flat back, elbows drive back, squeeze at top.',
  },
  {
    id: 'kb-bent-row',
    name: 'Kettlebell Bent-Over Row',
    equipment: ['kettlebell'],
    movementPattern: 'pull',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['lats', 'upper back'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-bent-row', 'ring-row'],
    coachingCue: 'Hinge at hips, pull KB to hip crease.',
  },

  // ── LUNGES ──────────────────────────────────────────────────────────────────
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    equipment: ['bodyweight'],
    movementPattern: 'lunge',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    defaultRepRange: [8, 16],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['air squat', 'step-up'],
    coachingCue: 'Step back, both knees 90°, front heel stays down.',
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    equipment: ['bodyweight'],
    movementPattern: 'lunge',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['reverse-lunge'],
    coachingCue: 'Long stride, upright torso, alternate legs.',
  },
  {
    id: 'db-walking-lunge',
    name: 'Dumbbell Walking Lunge',
    equipment: ['dumbbells'],
    movementPattern: 'lunge',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['walking-lunge', 'reverse-lunge'],
    coachingCue: 'DBs at sides, tall posture, controlled step.',
  },
  {
    id: 'jumping-lunge',
    name: 'Jumping Lunge',
    equipment: ['bodyweight'],
    movementPattern: 'lunge',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'calves'],
    defaultRepRange: [8, 16],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['reverse-lunge'],
    coachingCue: 'Explosive split jump, land soft, switch mid-air.',
  },
  {
    id: 'step-up',
    name: 'Box Step-Up',
    equipment: ['box'],
    movementPattern: 'lunge',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['reverse-lunge', 'air squat'],
    coachingCue: 'Full hip extension at top, control descent.',
  },

  // ── CORE ────────────────────────────────────────────────────────────────────
  {
    id: 'sit-up',
    name: 'Sit-Up',
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['core', 'hip flexors'],
    defaultRepRange: [10, 25],
    timeDomainFit: ['short', 'medium', 'long'],
    substitutions: ['hollow-hold', 'plank'],
    coachingCue: 'Butterfly feet, touch floor behind, reach to toes.',
  },
  {
    id: 'v-up',
    name: 'V-Up',
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['core', 'hip flexors'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['sit-up', 'hollow-hold'],
    coachingCue: 'Legs and arms meet at top, controlled lower.',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Hold',
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['core'],
    defaultRepRange: [20, 45],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['plank'],
    coachingCue: 'Lower back pressed to floor, legs low, shoulders off.',
  },
  {
    id: 'plank',
    name: 'Plank',
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['core', 'shoulders'],
    defaultRepRange: [20, 60],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['hollow-hold'],
    coachingCue: 'Rigid body, hips level, breathe steadily.',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['core', 'shoulders', 'hip flexors'],
    defaultRepRange: [20, 40],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['plank', 'sit-up'],
    coachingCue: 'Hips level, drive knees to chest alternately.',
  },
  {
    id: 'flutter-kick',
    name: 'Flutter Kick',
    equipment: ['bodyweight'],
    movementPattern: 'core',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['core', 'hip flexors'],
    defaultRepRange: [20, 50],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['hollow-hold', 'plank'],
    coachingCue: 'Lower back down, small controlled kicks, count each.',
  },
  {
    id: 'ghd-sit-up',
    name: 'GHD Sit-Up',
    equipment: ['ghd'],
    movementPattern: 'core',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['core', 'hip flexors', 'back'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['sit-up', 'v-up'],
    avoidForBeginner: true,
    coachingCue: 'Controlled full extension, hands touch plate behind.',
  },

  // ── JUMPS ───────────────────────────────────────────────────────────────────
  {
    id: 'box-jump',
    name: 'Box Jump',
    equipment: ['box'],
    movementPattern: 'jump',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'calves'],
    defaultRepRange: [5, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['step-up', 'broad-jump'],
    coachingCue: 'Full hip extension at top, step down for safety under fatigue.',
  },
  {
    id: 'broad-jump',
    name: 'Broad Jump',
    equipment: ['bodyweight'],
    movementPattern: 'jump',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes', 'calves'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['jump-squat', 'step-up'],
    coachingCue: 'Arm swing, explosive hips, land with soft knees.',
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jack',
    equipment: ['bodyweight'],
    movementPattern: 'jump',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['quads', 'calves', 'shoulders'],
    defaultRepRange: [20, 50],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['high-knees', 'step-jack'],
    coachingCue: 'Full arm overhead, feet wider than shoulder on jump.',
  },
  {
    id: 'skater-hop',
    name: 'Skater Hop',
    equipment: ['bodyweight'],
    movementPattern: 'jump',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['glutes', 'quads', 'calves'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['jumping-jack', 'reverse-lunge'],
    coachingCue: 'Lateral bound, land on one foot, touch ground with hand.',
  },

  // ── CONDITIONING / MONOSTRUCTURAL ──────────────────────────────────────────
  {
    id: 'burpee',
    name: 'Burpee',
    equipment: ['bodyweight'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['full body'],
    defaultRepRange: [5, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['step-back-burpee', 'push-up + air squat'],
    coachingCue: 'Chest and thighs to floor, jump with clap overhead.',
  },
  {
    id: 'step-back-burpee',
    name: 'Step-Back Burpee',
    equipment: ['bodyweight'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['full body'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['burpee'],
    coachingCue: 'Step feet back and forward instead of jumping, same chest touch.',
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    equipment: ['bodyweight'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['quads', 'core', 'calves'],
    defaultRepRange: [20, 50],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['jumping-jack', 'run'],
    coachingCue: 'Drive knees to hip height, pump arms.',
  },
  {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    equipment: ['bodyweight'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['core', 'shoulders', 'quads'],
    defaultRepRange: [10, 25],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['inchworm', 'mountain-climber'],
    coachingCue: 'Knees hover 1 inch off floor, opposite hand-foot move together.',
  },
  {
    id: 'inchworm',
    name: 'Inchworm',
    equipment: ['bodyweight'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'low',
    muscleGroups: ['hamstrings', 'core', 'shoulders'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short'],
    substitutions: ['bear-crawl'],
    coachingCue: 'Walk hands out to plank, walk feet to hands, stand.',
  },
  {
    id: 'run',
    name: 'Run',
    equipment: ['bodyweight'],
    movementPattern: 'monostructural',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['full body'],
    defaultRepRange: [200, 400],
    timeDomainFit: ['short', 'medium', 'long'],
    substitutions: ['row', 'bike', 'shuttle-run'],
    coachingCue: 'Consistent pace, breathe rhythmically.',
  },
  {
    id: 'shuttle-run',
    name: 'Shuttle Run',
    equipment: ['bodyweight'],
    movementPattern: 'monostructural',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'calves'],
    defaultRepRange: [3, 6],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['run', 'high-knees'],
    coachingCue: '5m there and back = 1 rep; touch the line each time.',
  },
  {
    id: 'row',
    name: 'Row (Rower)',
    equipment: ['rower'],
    movementPattern: 'monostructural',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['back', 'legs', 'core'],
    defaultRepRange: [250, 500],
    timeDomainFit: ['short', 'medium', 'long'],
    substitutions: ['bike', 'ski-erg', 'run'],
    coachingCue: 'Legs, body, arms — reverse on recovery. Drive with legs.',
  },
  {
    id: 'bike',
    name: 'Assault Bike',
    equipment: ['bike'],
    movementPattern: 'monostructural',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['legs', 'arms', 'core'],
    defaultRepRange: [10, 25],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['row', 'ski-erg', 'run'],
    coachingCue: 'Push and pull handles, drive with legs, consistent cadence.',
  },
  {
    id: 'ski-erg',
    name: 'Ski Erg',
    equipment: ['ski_erg'],
    movementPattern: 'monostructural',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['back', 'shoulders', 'core'],
    defaultRepRange: [10, 25],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['row', 'bike', 'run'],
    coachingCue: 'Hinge at hips, arms follow, full extension at top before pull.',
  },

  // ── JUMP ROPE ───────────────────────────────────────────────────────────────
  {
    id: 'single-under',
    name: 'Single-Under',
    equipment: ['jump_rope'],
    movementPattern: 'monostructural',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['calves', 'core'],
    defaultRepRange: [30, 100],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['double-under', 'jumping-jack'],
    coachingCue: 'Small jumps, wrists turn rope, land on balls of feet.',
  },
  {
    id: 'double-under',
    name: 'Double-Under',
    equipment: ['jump_rope'],
    movementPattern: 'monostructural',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['calves', 'core'],
    defaultRepRange: [20, 60],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['single-under', 'jumping-jack'],
    coachingCue: 'Slight pike, fast wrists, jump higher than singles.',
  },

  // ── OLYMPIC LIFTS ───────────────────────────────────────────────────────────
  {
    id: 'power-clean',
    name: 'Power Clean',
    equipment: ['barbell'],
    movementPattern: 'olympic_lift',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'traps', 'shoulders'],
    defaultRepRange: [3, 6],
    timeDomainFit: ['short'],
    substitutions: ['db-power-clean', 'kb-swing'],
    avoidForBeginner: true,
    coachingCue: 'Pull from floor, double extension, fast elbows, catch in quarter squat.',
    rxLoad: { male: '135 lb', female: '95 lb' },
  },
  {
    id: 'squat-clean',
    name: 'Squat Clean',
    equipment: ['barbell'],
    movementPattern: 'olympic_lift',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'quads', 'traps'],
    defaultRepRange: [2, 5],
    timeDomainFit: ['short'],
    substitutions: ['power-clean', 'db-power-clean'],
    avoidForBeginner: true,
    coachingCue: 'Pull, extension, drop under, catch in full squat, stand.',
    rxLoad: { male: '135 lb', female: '95 lb' },
  },
  {
    id: 'db-power-clean',
    name: 'Dumbbell Power Clean',
    equipment: ['dumbbells'],
    movementPattern: 'olympic_lift',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'traps'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['kb-swing', 'db-deadlift'],
    coachingCue: 'Hinge, shrug, pull under, catch at shoulders.',
    rxLoad: { male: '50 lb DBs', female: '35 lb DBs' },
  },
  {
    id: 'power-snatch',
    name: 'Power Snatch',
    equipment: ['barbell'],
    movementPattern: 'olympic_lift',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'shoulders'],
    defaultRepRange: [2, 5],
    timeDomainFit: ['short'],
    substitutions: ['db-snatch', 'kb-swing'],
    avoidForBeginner: true,
    coachingCue: 'Wide grip, big pull, punch overhead, catch with soft elbows.',
    rxLoad: { male: '95 lb', female: '65 lb' },
  },
  {
    id: 'db-snatch',
    name: 'Dumbbell Snatch',
    equipment: ['dumbbells'],
    movementPattern: 'olympic_lift',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'shoulders'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['kb-swing', 'db-power-clean'],
    coachingCue: 'One arm, hinge, shrug, pull, punch overhead, alternate each rep.',
    rxLoad: { male: '50 lb DB', female: '35 lb DB' },
  },

  // ── GYMNASTICS ──────────────────────────────────────────────────────────────
  {
    id: 'handstand-hold',
    name: 'Handstand Hold',
    equipment: ['bodyweight'],
    movementPattern: 'gymnastics',
    difficulty: 'advanced',
    intensity: 'moderate',
    muscleGroups: ['shoulders', 'core', 'wrists'],
    defaultRepRange: [15, 45],
    timeDomainFit: ['short'],
    substitutions: ['plank', 'pike-push-up'],
    avoidForBeginner: true,
    coachingCue: 'Kick up to wall, hollow body, eyes to floor.',
  },
  {
    id: 'wall-walk',
    name: 'Wall Walk',
    equipment: ['bodyweight'],
    movementPattern: 'gymnastics',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['shoulders', 'core', 'triceps'],
    defaultRepRange: [3, 8],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['pike-push-up', 'plank'],
    avoidForBeginner: true,
    coachingCue: 'Start in push-up, walk feet up wall, nose to wall at top.',
  },
  {
    id: 'ring-dip',
    name: 'Ring Dip',
    equipment: ['rings'],
    movementPattern: 'gymnastics',
    difficulty: 'advanced',
    intensity: 'moderate',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['push-up', 'bench-dip'],
    avoidForBeginner: true,
    coachingCue: 'Support on rings, dip below, lock out, rings turned out.',
  },

  // ── CARRY ───────────────────────────────────────────────────────────────────
  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    equipment: ['dumbbells', 'kettlebell'],
    movementPattern: 'carry',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['forearms', 'traps', 'core', 'legs'],
    defaultRepRange: [20, 50],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-deadlift'],
    coachingCue: 'Tall posture, tight grip, small quick steps.',
  },
  {
    id: 'sandbag-carry',
    name: 'Sandbag Carry',
    equipment: ['sandbag'],
    movementPattern: 'carry',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['core', 'traps', 'legs'],
    defaultRepRange: [20, 50],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['farmers-carry'],
    coachingCue: 'Bear hug or shoulder carry, brace core throughout.',
  },

  // ── MEDICINE BALL ───────────────────────────────────────────────────────────
  {
    id: 'med-ball-clean',
    name: 'Medicine Ball Clean',
    equipment: ['medicine_ball'],
    movementPattern: 'olympic_lift',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['hamstrings', 'glutes', 'traps'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['db-power-clean'],
    coachingCue: 'Deadlift, shrug, pull under, catch in front rack squat.',
  },
  {
    id: 'med-ball-slam',
    name: 'Medicine Ball Slam',
    equipment: ['medicine_ball'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['shoulders', 'core', 'lats'],
    defaultRepRange: [8, 15],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['burpee'],
    coachingCue: 'Overhead, full extension, slam hard, catch on bounce.',
  },

  // ── BENCH ───────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Bench Press',
    equipment: ['barbell', 'bench'],
    movementPattern: 'push',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    defaultRepRange: [5, 10],
    timeDomainFit: ['short'],
    substitutions: ['push-up', 'db-floor-press'],
    coachingCue: 'Arch, retract scapula, bar to chest, press explosively.',
    rxLoad: { male: '135 lb', female: '95 lb' },
  },
  {
    id: 'db-floor-press',
    name: 'Dumbbell Floor Press',
    equipment: ['dumbbells'],
    movementPattern: 'push',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['chest', 'triceps'],
    defaultRepRange: [8, 12],
    timeDomainFit: ['short'],
    substitutions: ['push-up', 'bench-press'],
    coachingCue: 'Elbows 45°, press to lockout, lower until triceps touch floor.',
  },
  {
    id: 'box-step-over',
    name: 'Box Step-Over',
    equipment: ['box'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['quads', 'glutes', 'core'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['step-up', 'box-jump'],
    coachingCue: 'Step up, stand tall on top, step down other side.',
  },

  // ── ROPE ────────────────────────────────────────────────────────────────────
  {
    id: 'rope-climb',
    name: 'Rope Climb',
    equipment: ['rope'],
    movementPattern: 'pull',
    difficulty: 'intermediate',
    intensity: 'high',
    muscleGroups: ['lats', 'biceps', 'forearms', 'core'],
    defaultRepRange: [1, 5],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['pull-up', 'ring-row'],
    avoidForBeginner: true,
    coachingCue: 'S-wrap the rope with your feet, stand up tall, repeat.',
  },
  {
    id: 'legless-rope-climb',
    name: 'Legless Rope Climb',
    equipment: ['rope'],
    movementPattern: 'pull',
    difficulty: 'advanced',
    intensity: 'high',
    muscleGroups: ['lats', 'biceps', 'forearms', 'core'],
    defaultRepRange: [1, 3],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['rope-climb', 'strict-pull-up'],
    avoidForBeginner: true,
    coachingCue: 'Arms only — keep legs off the rope, pull high and reset.',
  },

  // ── GHD ─────────────────────────────────────────────────────────────────────
  {
    id: 'ghd-hip-extension',
    name: 'GHD Hip Extension',
    equipment: ['ghd'],
    movementPattern: 'hinge',
    difficulty: 'beginner',
    intensity: 'moderate',
    muscleGroups: ['glutes', 'hamstrings', 'lower back'],
    defaultRepRange: [15, 25],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['good-morning', 'back-extension'],
    coachingCue: 'Neutral spine, hinge at hip, squeeze glutes at top.',
  },
  {
    id: 'ghd-back-extension',
    name: 'GHD Back Extension',
    equipment: ['ghd'],
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    intensity: 'moderate',
    muscleGroups: ['lower back', 'glutes', 'hamstrings'],
    defaultRepRange: [10, 20],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['good-morning', 'romanian-deadlift'],
    coachingCue: 'Slow descent, neutral neck, extend fully without hyperextending.',
  },

  // ── SLED ────────────────────────────────────────────────────────────────────
  {
    id: 'sled-push',
    name: 'Sled Push',
    equipment: ['sled'],
    movementPattern: 'conditioning',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['quads', 'glutes', 'calves', 'core'],
    defaultRepRange: [1, 4],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['prowler-push', 'bear-crawl'],
    coachingCue: 'Drive through the floor, lean into the sled, short quick steps.',
  },
  {
    id: 'sled-pull',
    name: 'Sled Pull',
    equipment: ['sled'],
    movementPattern: 'pull',
    difficulty: 'beginner',
    intensity: 'high',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'core'],
    defaultRepRange: [1, 4],
    timeDomainFit: ['short', 'medium'],
    substitutions: ['sled-push', 'farmers-carry'],
    coachingCue: 'Face away, pull strap hand-over-hand or drag walking backward.',
  },
]
