import type { WodTemplate } from './types'

export const TEMPLATES: WodTemplate[] = [
  // ── AMRAP ───────────────────────────────────────────────────────────────────
  {
    id: 'short-amrap-triplet',
    name: 'Short AMRAP Triplet',
    format: 'AMRAP',
    durationRange: [8, 12],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'high' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'medium-amrap-triplet',
    name: 'Medium AMRAP Triplet',
    format: 'AMRAP',
    durationRange: [15, 20],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'pull', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'high' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'amrap-couplet',
    name: 'AMRAP Couplet',
    format: 'AMRAP',
    durationRange: [8, 15],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'hinge', repScheme: 'medium' },
      { pattern: 'conditioning', repScheme: 'medium' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'amrap-quad',
    name: 'AMRAP Quad',
    format: 'AMRAP',
    durationRange: [15, 25],
    allowedIntensity: ['low', 'moderate'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'high' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'amrap-strength-bias',
    name: 'Strength-Bias AMRAP',
    format: 'AMRAP',
    durationRange: [10, 15],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'hinge', repScheme: 'low' },
      { pattern: 'push', repScheme: 'low' },
      { pattern: 'pull', repScheme: 'low' },
    ],
    scoreType: 'rounds_reps',
  },

  // ── EMOM ────────────────────────────────────────────────────────────────────
  {
    id: 'emom-balanced',
    name: 'Balanced EMOM',
    format: 'EMOM',
    durationRange: [16, 24],
    allowedIntensity: ['low', 'moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'hinge', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'time' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'completed',
  },
  {
    id: 'emom-triplet',
    name: 'EMOM Triplet',
    format: 'EMOM',
    durationRange: [12, 18],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'completed',
  },
  {
    id: 'emom-upper-lower',
    name: 'Upper / Lower EMOM',
    format: 'EMOM',
    durationRange: [16, 20],
    allowedIntensity: ['low', 'moderate'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'pull', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'time' },
    ],
    scoreType: 'completed',
  },
  {
    id: 'emom-short-blast',
    name: 'Short EMOM Blast',
    format: 'EMOM',
    durationRange: [8, 12],
    allowedIntensity: ['high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'completed',
  },

  // ── FOR TIME ────────────────────────────────────────────────────────────────
  {
    id: 'for-time-couplet',
    name: 'For-Time Couplet',
    format: 'For Time',
    durationRange: [8, 15],
    allowedIntensity: ['high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'conditioning', repScheme: 'high' },
      { pattern: 'squat', repScheme: 'high' },
    ],
    scoreType: 'time',
  },
  {
    id: 'for-time-triplet',
    name: 'For-Time Triplet',
    format: 'For Time',
    durationRange: [10, 20],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'high' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'distance' },
    ],
    scoreType: 'time',
  },
  {
    id: 'chipper',
    name: 'Chipper',
    format: 'For Time',
    durationRange: [20, 35],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'monostructural', repScheme: 'distance' },
      { pattern: 'squat', repScheme: 'high' },
      { pattern: 'pull', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'high' },
    ],
    scoreType: 'time',
  },
  {
    id: 'rounds-for-time',
    name: 'Rounds For Time',
    format: 'For Time',
    durationRange: [12, 25],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'medium' },
    ],
    scoreType: 'time',
  },

  // ── INTERVALS ───────────────────────────────────────────────────────────────
  {
    id: 'intervals-short',
    name: 'Short Intervals',
    format: 'Intervals',
    durationRange: [8, 15],
    allowedIntensity: ['high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'monostructural', repScheme: 'calories' },
      { pattern: 'conditioning', repScheme: 'medium' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'intervals-rest-work',
    name: 'Work / Rest Intervals',
    format: 'Intervals',
    durationRange: [12, 20],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'monostructural', repScheme: 'calories' },
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'intervals-long',
    name: 'Long Intervals',
    format: 'Intervals',
    durationRange: [20, 40],
    allowedIntensity: ['low', 'moderate'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'monostructural', repScheme: 'distance' },
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'hinge', repScheme: 'medium' },
    ],
    scoreType: 'rounds_reps',
  },

  // ── STRENGTH + METCON ────────────────────────────────────────────────────────
  {
    id: 'strength-metcon-lower',
    name: 'Lower Strength + Metcon',
    format: 'Strength + Metcon',
    durationRange: [30, 50],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'low' },
      { pattern: 'hinge', repScheme: 'low' },
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'load',
  },
  {
    id: 'strength-metcon-upper',
    name: 'Upper Strength + Metcon',
    format: 'Strength + Metcon',
    durationRange: [30, 50],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'push', repScheme: 'low' },
      { pattern: 'pull', repScheme: 'low' },
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'load',
  },
  {
    id: 'strength-metcon-olympic',
    name: 'Olympic + Metcon',
    format: 'Strength + Metcon',
    durationRange: [30, 60],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['advanced'],
    movementSlots: [
      { pattern: 'olympic_lift', repScheme: 'low' },
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'load',
  },

  {
    id: 'amrap-five',
    name: 'Five-Movement AMRAP',
    format: 'AMRAP',
    durationRange: [20, 35],
    allowedIntensity: ['low', 'moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'pull', repScheme: 'medium' },
      { pattern: 'hinge', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'high' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'for-time-five',
    name: 'Five-Movement Rounds For Time',
    format: 'For Time',
    durationRange: [20, 35],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'pull', repScheme: 'medium' },
      { pattern: 'hinge', repScheme: 'medium' },
      { pattern: 'conditioning', repScheme: 'medium' },
    ],
    scoreType: 'time',
  },

  // ── BODYWEIGHT-SPECIFIC ──────────────────────────────────────────────────────
  {
    id: 'bodyweight-short-amrap',
    name: 'Bodyweight Short AMRAP',
    format: 'AMRAP',
    durationRange: [8, 15],
    allowedIntensity: ['low', 'moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'medium' },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'bodyweight-emom',
    name: 'Bodyweight EMOM',
    format: 'EMOM',
    durationRange: [12, 18],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'squat', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'time' },
    ],
    scoreType: 'completed',
  },
  {
    id: 'bodyweight-chipper',
    name: 'Bodyweight Chipper',
    format: 'For Time',
    durationRange: [15, 30],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'conditioning', repScheme: 'high' },
      { pattern: 'squat', repScheme: 'high' },
      { pattern: 'push', repScheme: 'medium' },
      { pattern: 'core', repScheme: 'high' },
    ],
    scoreType: 'time',
  },

  // ── BENCHMARK ARCHETYPES ─────────────────────────────────────────────────────
  // These force a specific rep scheme to match canonical CrossFit WOD patterns.
  {
    id: 'fran-style',
    name: 'Fran-Style 21-15-9',
    format: 'For Time',
    durationRange: [8, 15],
    allowedIntensity: ['high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'push', repScheme: 'medium', repSchemeOverride: { kind: 'descending_ladder', sets: [21, 15, 9] } },
      { pattern: 'pull', repScheme: 'medium', repSchemeOverride: { kind: 'descending_ladder', sets: [21, 15, 9] } },
    ],
    scoreType: 'time',
  },
  {
    id: '21-15-9-triplet',
    name: '21-15-9 Triplet',
    format: 'For Time',
    durationRange: [10, 20],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'medium', repSchemeOverride: { kind: 'descending_ladder', sets: [21, 15, 9] } },
      { pattern: 'push', repScheme: 'medium', repSchemeOverride: { kind: 'descending_ladder', sets: [21, 15, 9] } },
      { pattern: 'pull', repScheme: 'medium', repSchemeOverride: { kind: 'descending_ladder', sets: [21, 15, 9] } },
    ],
    scoreType: 'time',
  },
  {
    id: 'grace-style',
    name: 'Grace-Style Single Movement',
    format: 'For Time',
    durationRange: [8, 12],
    allowedIntensity: ['high'],
    allowedSkillLevels: ['advanced'],
    movementSlots: [
      { pattern: 'olympic_lift', repScheme: 'high', repSchemeOverride: { kind: 'single_set', reps: 30 } },
    ],
    scoreType: 'time',
  },
  {
    id: 'helen-style',
    name: 'Helen-Style 3 Rounds',
    format: 'For Time',
    durationRange: [10, 20],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'monostructural', repScheme: 'distance', repSchemeOverride: { kind: 'fixed_rounds', rounds: 3, reps: 1 } },
      { pattern: 'hinge', repScheme: 'medium', repSchemeOverride: { kind: 'fixed_rounds', rounds: 3, reps: 21 } },
      { pattern: 'pull', repScheme: 'medium', repSchemeOverride: { kind: 'fixed_rounds', rounds: 3, reps: 12 } },
    ],
    scoreType: 'time',
  },
  {
    id: 'dt-style',
    name: 'DT-Style 5 Rounds Barbell',
    format: 'For Time',
    durationRange: [15, 25],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'hinge', repScheme: 'medium', repSchemeOverride: { kind: 'fixed_rounds', rounds: 5, reps: 12 } },
      { pattern: 'olympic_lift', repScheme: 'medium', repSchemeOverride: { kind: 'fixed_rounds', rounds: 5, reps: 9 } },
      { pattern: 'push', repScheme: 'low', repSchemeOverride: { kind: 'fixed_rounds', rounds: 5, reps: 6 } },
    ],
    scoreType: 'time',
  },
  {
    id: 'cindy-style',
    name: 'Cindy-Style AMRAP',
    format: 'AMRAP',
    durationRange: [15, 25],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['beginner', 'intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'pull', repScheme: 'low', repSchemeOverride: { kind: 'single_set', reps: 5 } },
      { pattern: 'push', repScheme: 'medium', repSchemeOverride: { kind: 'single_set', reps: 10 } },
      { pattern: 'squat', repScheme: 'medium', repSchemeOverride: { kind: 'single_set', reps: 15 } },
    ],
    scoreType: 'rounds_reps',
  },
  {
    id: 'chipper-heavy',
    name: 'Heavy Chipper',
    format: 'For Time',
    durationRange: [20, 40],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'monostructural', repScheme: 'calories' },
      { pattern: 'squat', repScheme: 'high', repSchemeOverride: { kind: 'single_set', reps: 50 } },
      { pattern: 'pull', repScheme: 'medium', repSchemeOverride: { kind: 'single_set', reps: 40 } },
      { pattern: 'push', repScheme: 'medium', repSchemeOverride: { kind: 'single_set', reps: 30 } },
      { pattern: 'conditioning', repScheme: 'high', repSchemeOverride: { kind: 'single_set', reps: 20 } },
      { pattern: 'core', repScheme: 'medium', repSchemeOverride: { kind: 'single_set', reps: 30 } },
    ],
    scoreType: 'time',
  },
  {
    id: '5x5-strength',
    name: '5x5 Strength + Metcon',
    format: 'Strength + Metcon',
    durationRange: [30, 50],
    allowedIntensity: ['moderate', 'high'],
    allowedSkillLevels: ['intermediate', 'advanced'],
    movementSlots: [
      { pattern: 'squat', repScheme: 'low', repSchemeOverride: { kind: 'fixed_rounds', rounds: 5, reps: 5 } },
      { pattern: 'hinge', repScheme: 'low', repSchemeOverride: { kind: 'fixed_rounds', rounds: 5, reps: 5 } },
      { pattern: 'conditioning', repScheme: 'medium' },
      { pattern: 'monostructural', repScheme: 'calories' },
    ],
    scoreType: 'load',
  },
]
